/* Generated By:JavaCC: Do not edit this line. practica2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practica2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 7;
  /** RegularExpression Id. */
  int INICIO = 8;
  /** RegularExpression Id. */
  int FIN = 9;
  /** RegularExpression Id. */
  int PUNTO = 10;
  /** RegularExpression Id. */
  int COMA = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int NUM = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"PROGRAM\"",
    "\"BEGIN\"",
    "\"END\"",
    "\".\"",
    "\",\"",
    "<ID>",
    "<NUM>",
  };

}
