/* Generated By:JavaCC: Do not edit this line. practica2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practica2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 7;
  /** RegularExpression Id. */
  int INICIO = 8;
  /** RegularExpression Id. */
  int FIN = 9;
  /** RegularExpression Id. */
  int PUNTO = 10;
  /** RegularExpression Id. */
  int COMA = 11;
  /** RegularExpression Id. */
  int MUEVE = 12;
  /** RegularExpression Id. */
  int A = 13;
  /** RegularExpression Id. */
  int SUMA = 14;
  /** RegularExpression Id. */
  int RESTA = 15;
  /** RegularExpression Id. */
  int DE = 16;
  /** RegularExpression Id. */
  int MULTIPLICA = 17;
  /** RegularExpression Id. */
  int POR = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int LEE = 20;
  /** RegularExpression Id. */
  int MUESTRA = 21;
  /** RegularExpression Id. */
  int SI = 22;
  /** RegularExpression Id. */
  int ENTONCES = 23;
  /** RegularExpression Id. */
  int SINO = 24;
  /** RegularExpression Id. */
  int ES = 25;
  /** RegularExpression Id. */
  int NO = 26;
  /** RegularExpression Id. */
  int MAYOR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int QUE = 29;
  /** RegularExpression Id. */
  int IGUAL = 30;
  /** RegularExpression Id. */
  int MIENTRAS = 31;
  /** RegularExpression Id. */
  int HACER = 32;
  /** RegularExpression Id. */
  int VARYING = 33;
  /** RegularExpression Id. */
  int DANDO = 34;
  /** RegularExpression Id. */
  int ENTRE = 35;
  /** RegularExpression Id. */
  int MAS = 36;
  /** RegularExpression Id. */
  int MENOS = 37;
  /** RegularExpression Id. */
  int MULT = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int PA = 40;
  /** RegularExpression Id. */
  int PC = 41;
  /** RegularExpression Id. */
  int ID = 42;
  /** RegularExpression Id. */
  int NUM = 43;
  /** RegularExpression Id. */
  int CAD = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"PROGRAM\"",
    "\"BEGIN\"",
    "\"END\"",
    "\".\"",
    "\",\"",
    "\"MOVE\"",
    "\"TO\"",
    "\"ADD\"",
    "\"SUBTRACT\"",
    "\"FROM\"",
    "\"MULTIPLY\"",
    "\"BY\"",
    "\"DIVIDE\"",
    "\"ACCEPT\"",
    "\"DISPLAY\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"IS\"",
    "\"NOT\"",
    "\"GREATER\"",
    "\"LESS\"",
    "\"THAN\"",
    "\"EQUAL\"",
    "\"WHILE\"",
    "\"DO\"",
    "\"VARYING\"",
    "\"GIVING\"",
    "\"INTO\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<ID>",
    "<NUM>",
    "<CAD>",
  };

}
